;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-exit-visual-state
        evil-forward-char
        evil-insert
        evil-mc-make-and-goto-next-match
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-ret
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        evil-delete-backward-char-and-join
        evil-paste-last-insertion
        ))
